@startuml
class Backgroundtile {
    + hitPoints : int
    - spriteRenderer : SpriteRenderer
    + breakSprite : Sprite
    - Start() : void
    - Update() : void
    + TakeDamage(damage:int) : void
    - MakeBreakColor() : void
    - MakeBreakSprite() : void
}
MonoBehaviour <|-- Backgroundtile
@enduml
