@startuml
class BlankGoal {
    + numberNeeded : int
    + numberCollected : int
    + goalSprite : Sprite
    + matchValue : string
}
class GoalManager {
    + levelGoals : BlankGoal[]
    + goalPrefab : GameObject
    + goalIntroParent : GameObject
    + goalGameParent : GameObject
    - Start() : void
    - SetupIntroGoals() : void
    - Update() : void
}
MonoBehaviour <|-- GoalManager
@enduml
