@startuml
class GoalPanel {
    + thisImage : Image
    + thisSprite : Sprite
    + thisText : TextMeshProUGUI
    + thisString : string
    - Start() : void
    - Setup() : void
    - Update() : void
}
MonoBehaviour <|-- GoalPanel
@enduml
