@startuml
class SoundManager {
    + destroyNoise : AudioSource[]
    + backgroundMusic : AudioSource
    + introSection : AudioSource
    - introPlayed : bool = false
    + Start() : void
    + Update() : void
    - PlayBackground() : void
    - CheckPlayIntroToPlayBG() : void
    - PlayIntro() : void
    + PlayRandomDestroyNoise() : void
}
MonoBehaviour <|-- SoundManager
@enduml
